# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ajout.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QMainWindow,QLineEdit,QAction
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import sqlite3
import os
import sys


# Obtenez le chemin absolu du répertoire du script
script_dir = os.path.dirname(os.path.abspath(__file__))
database_path = os.path.join(script_dir, "LARISSA.db")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 313)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 471, 271))
        self.frame.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QLabel{\n"
"color: #FF6600;\n"
"}\n"
"\n"
"QLabel#label{\n"
"color:#000;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"border-bottom: 2px solid #cccccc;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-bottom: 2px solid #FF6600;\n"
"}")
        self.frame.setObjectName("frame")
        self.btnAnnuler = QtWidgets.QPushButton(self.frame)
        self.btnAnnuler.setGeometry(QtCore.QRect(9, 240, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnAnnuler.setFont(font)
        self.btnAnnuler.setStyleSheet("border: none;")
        self.btnAnnuler.setObjectName("btnAnnuler")
        self.btnAjouter = QtWidgets.QPushButton(self.frame)
        self.btnAjouter.setGeometry(QtCore.QRect(70, 240, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnAjouter.setFont(font)
        self.btnAjouter.setStyleSheet("border: none;")
        self.btnAjouter.setObjectName("btnAjouter")
        self.labelTexte = QtWidgets.QLabel(self.frame)
        self.labelTexte.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTexte.setFont(font)
        self.labelTexte.setStyleSheet("color:black;")
        self.labelTexte.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTexte.setObjectName("labelTexte")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 120, 201, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTelephone = QtWidgets.QLabel(self.layoutWidget)
        self.labelTelephone.setObjectName("labelTelephone")
        self.verticalLayout.addWidget(self.labelTelephone)
        self.inputTelephone = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputTelephone.setStyleSheet("border-radius:none;")
        self.inputTelephone.setObjectName("inputTelephone")
        self.verticalLayout.addWidget(self.inputTelephone)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 70, 201, 39))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelNom = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelNom.setObjectName("labelNom")
        self.verticalLayout_2.addWidget(self.labelNom)
        self.inputNom = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.inputNom.setStyleSheet("border-radius:none;")
        self.inputNom.setObjectName("inputNom")
        self.verticalLayout_2.addWidget(self.inputNom)
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(240, 170, 201, 39))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelDescription = QtWidgets.QLabel(self.layoutWidget_5)
        self.labelDescription.setObjectName("labelDescription")
        self.verticalLayout_5.addWidget(self.labelDescription)
        self.inputDescription = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.inputDescription.setStyleSheet("border-radius:none;")
        self.inputDescription.setObjectName("inputDescription")
        self.verticalLayout_5.addWidget(self.inputDescription)
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 170, 201, 39))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelActivite = QtWidgets.QLabel(self.layoutWidget_6)
        self.labelActivite.setObjectName("labelActivite")
        self.verticalLayout_6.addWidget(self.labelActivite)
        self.inputActivite = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.inputActivite.setStyleSheet("border-radius:none;")
        self.inputActivite.setObjectName("inputActivite")
        self.verticalLayout_6.addWidget(self.inputActivite)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(240, 120, 201, 39))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelDate = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelDate.setObjectName("labelDate")
        self.verticalLayout_3.addWidget(self.labelDate)
        self.inputDate = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.inputDate.setStyleSheet("border-radius:none;")
        self.inputDate.setObjectName("inputDate")
        self.verticalLayout_3.addWidget(self.inputDate)
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_4.setGeometry(QtCore.QRect(240, 70, 201, 39))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelEmail = QtWidgets.QLabel(self.layoutWidget_4)
        self.labelEmail.setObjectName("labelEmail")
        self.verticalLayout_4.addWidget(self.labelEmail)
        self.inputEmail = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.inputEmail.setStyleSheet("border-radius:none;")
        self.inputEmail.setObjectName("inputEmail")
        self.verticalLayout_4.addWidget(self.inputEmail)
        
        
        
        
        self.nom_label = self.labelNom
        self.telephone_label = self.labelTelephone
        self.activite_label = self.labelActivite
        self.date_label = self.labelDate
        self.email_label = self.labelEmail
        self.description_label = self.labelDescription

        self.nom_label.setText("")
        self.telephone_label.setText("")
        self.activite_label.setText("")
        self.date_label.setText("")
        self.email_label.setText("")
        self.description_label.setText("")


        self.nom_input = self.inputNom
        self.telephone_input = self.inputTelephone
        self.activite_input = self.inputActivite
        self.date_input = self.inputDate
        self.email_input = self.inputEmail
        self.description_input = self.inputDescription


        self.nom_input.setPlaceholderText("Nom*")
        self.telephone_input.setPlaceholderText("Téléphone*")
        self.activite_input.setPlaceholderText("Activité*")
        self.date_input.setPlaceholderText("Date*")
        self.email_input.setPlaceholderText("Email*")
        self.description_input.setPlaceholderText("Description*")


        self.nom_input.setClearButtonEnabled(True)
        self.telephone_input.setClearButtonEnabled(True)
        self.activite_input.setClearButtonEnabled(True)
        self.date_input.setClearButtonEnabled(True)
        self.email_input.setClearButtonEnabled(True)
        self.description_input.setClearButtonEnabled(True)


        self.btnAjouter.setEnabled(False)

        icon = QIcon(":icons/UI/x2.svg")
        self.nom_input.findChildren(QAction)[0].setIcon(icon)
        self.telephone_input.findChildren(QAction)[0].setIcon(icon)
        self.activite_input.findChildren(QAction)[0].setIcon(icon)
        self.date_input.findChildren(QAction)[0].setIcon(icon)
        self.email_input.findChildren(QAction)[0].setIcon(icon)
        self.description_input.findChildren(QAction)[0].setIcon(icon)


        self.nom_input.textChanged.connect(self.do_nom_label)
        self.telephone_input.textChanged.connect(self.do_telephone_label)
        self.inputActivite.textChanged.connect(self.do_Activite_label)
        self.inputEmail.textChanged.connect(self.do_email_label)
        self.inputDate.textChanged.connect(self.do_date_label)
        self.inputDescription.textChanged.connect(self.do_description_label)





        self.inputNom.textChanged.connect(self.checkFields)
        self.inputTelephone.textChanged.connect(self.checkFields)
        self.inputActivite.textChanged.connect(self.checkFields)
        self.inputDate.textChanged.connect(self.checkFields)
        self.inputEmail.textChanged.connect(self.checkFields)
        self.inputDescription.textChanged.connect(self.checkFields)



        self.btnAnnuler.clicked.connect(MainWindow.close)
        self.btnAjouter.clicked.connect(self.ajouter)
        self.btnAjouter.clicked.connect(MainWindow.close)
        
        
        
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
    def ajouter(self):
        
        Nom = self.inputNom.text()
        Telephone = self.inputTelephone.text()
        Activite = self.inputActivite.text()
        Date = self.inputDate.text()
        Email = self.inputEmail.text()
        Description = self.inputDescription.text()
                     
        
        # connexion à la base de données
        con = sqlite3.connect(database_path)
        cur = con.cursor()
        cur.execute("insert into Prospects (Nom,Telephone,Email,Activite,Date,Description)values (?,?,?,?,?,?)", (Nom,Telephone,Email,Activite,Date,Description))
        RqtResult = cur.fetchall()
        con.commit()   
        
        con.close()    
        
        self.inputNom.setText("")
        self.inputTelephone.setText("")
        self.inputActivite.setText("")
        self.inputDate.setText("")
        self.inputEmail.setText("")
        self.inputDescription.setText("")    
        
        

    
    def do_nom_label(self, text):
        if text:
            self.nom_label.setText("Nom*")
            
        else:
            self.nom_label.setText("")
            
    def do_telephone_label(self, text):
        if text:
            self.telephone_label.setText("Téléphone*")
            
        else:
            self.telephone_label.setText("")
            
    def do_Activite_label(self, text):
        if text:
            self.activite_label.setText("Activité*")
            
        else:
            self.activite_label.setText("")
            
    def do_date_label(self, text):
        if text:
            self.date_label.setText("Date*")
            
        else:
            self.date_label.setText("")
            
    def do_email_label(self, text):
        if text:
            self.email_label.setText("Email*")
            
        else:
            self.email_label.setText("")
            
    def do_description_label(self, text):
        if text:
            self.description_label.setText("Description*")
            
        else:
            self.description_label.setText("")
            
            
    def checkFields(self):
        nom_text = self.inputNom.text()
        telephone_text = self.inputTelephone.text()
        activite_text = self.inputActivite.text()
        date_text = self.inputDate.text()
        email_text = self.inputEmail.text()
        description_text = self.inputDescription.text()
        
        enable_button = bool(nom_text and telephone_text and activite_text and date_text and email_text and description_text)
        self.btnAjouter.setEnabled(enable_button)
        
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAnnuler.setText(_translate("MainWindow", "Annuler"))
        self.btnAjouter.setText(_translate("MainWindow", "Ajouter"))
        self.labelTexte.setText(_translate("MainWindow", "Ajout Prospect"))
        self.labelTelephone.setText(_translate("MainWindow", ""))
        self.labelNom.setText(_translate("MainWindow", ""))
        self.labelDescription.setText(_translate("MainWindow", ""))
        self.labelActivite.setText(_translate("MainWindow", ""))
        self.labelDate.setText(_translate("MainWindow", ""))
        self.labelEmail.setText(_translate("MainWindow", ""))

import resources_rc

if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
